export const WORKSPACE_INSTRUCTIONS = `DODO uses the connected client's OAuth scopes (HTTP), workspace access and local trust settings. Start with project_overview to get the active workspace and its capabilities. Pass workspaceId and workspaceEpoch from that overview to other tools; refresh overview after restart or a local owner workspace switch. project_overview also lists owner-registered projects this client may read: use projectId on project_overview/list_files/read_files or projectId/projectIds on search_code for bounded read-only federation without changing the active workspace. Target project identity and source hashes are evidence; switch through owner-only Local Config and re-read before editing or executing there. Use bounded reads/search, preview and expected hashes for edits, and job polling for long commands. Respect local approval errors, secret/path guards and separate Desktop permissions. Commands in trusted mode execute with OS-user privileges unless sandboxed. Scheduled commands require local owner approval of their immutable specification before execution. Do not use exec or desktop to approve yourself or change owner security settings.`;

export const COMPACT_INSTRUCTIONS = `${WORKSPACE_INSTRUCTIONS} This connection uses the COMPACT tool surface: a few dodo_* gateway tools cover every capability. Choose the gateway for the domain (dodo_read/dodo_write/dodo_exec for code, dodo_git_*, dodo_desktop_*, dodo_assist_*, dodo_media, dodo_browser, dodo_game, dodo_workflow_*, dodo_schedule, dodo_web), set operation to the target operation and put its own arguments in args. Use dodo_discover when you need a capability not obvious from a gateway's operation list, or to fetch an operation's exact input schema before calling it. Gateways change nothing about permissions: the target operation's scope, trust policy, approvals and guards apply exactly as if called directly.`;

export const HYBRID_INSTRUCTIONS = `${WORKSPACE_INSTRUCTIONS} This connection uses the HYBRID tool surface: the most common coding tools (read/write/edit/search/git/run/jobs) are available directly under their own names, and EVERY other capability (assistance, desktop, media, browser, game, workflow, schedule, web fetch, todos/handoff/diagnostics) is reached through the dodo_* gateway tools — set operation to the target operation and put its own arguments in args. Use dodo_discover to find an operation or fetch its exact args schema. Gateways change nothing about permissions: the target operation's scope, trust policy, approvals and guards apply exactly as if called directly.`;

export function instructionsFor(surface: 'compact' | 'full' | 'hybrid'): string {
  if (surface === 'compact') return COMPACT_INSTRUCTIONS;
  if (surface === 'hybrid') return HYBRID_INSTRUCTIONS;
  return WORKSPACE_INSTRUCTIONS;
}
