import fs from 'node:fs';
import path from 'node:path';
import net from 'node:net';
import { execFileSync } from 'node:child_process';
import { newId } from '../../src/util/hash.js';
import { randomUUID } from 'node:crypto';
import { afterEach, describe, expect, it } from 'vitest';
import { platformFixture } from '../helpers/platform.js';
import { ProjectRegistry } from '../../src/projects/registry.js';
import { createIpcDispatcher } from '../../src/server/ipcDispatch.js';
import { VerificationSchema } from '../../src/services/assistance/verification.js';

// Product adapter acceptance against a disposable service. The test process itself is native.
describe.skipIf(process.env['DODO_TEST_DEPLOYMENT_DOCKER'] !== '1')('R05 real Docker deployment adapter', () => {
  let f: ReturnType<typeof platformFixture>, dockerContext: string;
  const containers = new Set<string>(), images = new Set<string>(), tags = new Set<string>();
  let composeProject: string | undefined, volume: string | undefined;
  const docker = (args: string[]) => execFileSync('docker', ['--context', dockerContext, ...args], { encoding: 'utf8', timeout: 30000, stdio: ['ignore', 'pipe', 'pipe'] }).trim();
  afterEach(async () => {
    // This namespace is newly generated by this fixture; never enumerate/delete unrelated resources.
    if (composeProject && dockerContext) {
      const ids = docker(['container', 'ls', '--all', '--no-trunc', '--filter', `label=com.docker.compose.project=${composeProject}`, '--format', '{{.ID}}']);
      for (const id of ids.split('\n').filter(Boolean)) containers.add(id);
    }
    for (const id of containers) { try { docker(['container', 'rm', '--force', id]); } catch { /* already replaced by this fixture's Compose up */ } }
    for (const tag of tags) { try { docker(['image', 'rm', tag]); } catch { /* diagnostic state remains if removal is unavailable */ } }
    for (const id of images) { try { docker(['image', 'rm', id]); } catch { /* fixture-only image IDs, never prune */ } }
    if (composeProject) { try { docker(['network', 'rm', `${composeProject}_default`]); } catch { /* still in use or absent, never force */ } }
    if(volume){try{docker(['volume','rm',volume]);}catch{/* only this disposable fixture volume */}}
    await f?.close();
  });
  async function freePort() {
    const server = net.createServer(); await new Promise<void>(resolve => server.listen(0, '127.0.0.1', resolve));
    const port = (server.address() as net.AddressInfo).port; await new Promise<void>(resolve => server.close(() => resolve())); return port;
  }
  it('builds verified source, inspects actual image bytes, deploys and stabilizes; drift and failed health preserve the known-good pointer', async () => {
    dockerContext = execFileSync('docker', ['context', 'show'], { encoding: 'utf8' }).trim();
    docker(['info', '--format', '{{.ServerVersion}}']);
    f = platformFixture(); composeProject = 'dodo-r05-' + randomUUID().slice(0, 8);
    volume = composeProject + '-data';docker(['volume','create',volume]);
    const volumeCommand=(source:string)=>docker(['run','--rm','--network','none','--mount',`type=volume,src=${volume},dst=/data`,'node:24-alpine','node','-e',source]);
    volumeCommand(`const db=new(require('node:sqlite').DatabaseSync)('/data/fixture.db');db.exec('CREATE TABLE orders(id INTEGER,quota INTEGER);INSERT INTO orders VALUES(1,73);CREATE TABLE migrations(id TEXT);');db.prepare('INSERT INTO migrations VALUES(?)').run('v1');require('fs').writeFileSync('/data/private-config','fixture-only-secret');`);
    const databaseState=()=>volumeCommand(`const db=new(require('node:sqlite').DatabaseSync)('/data/fixture.db',{readOnly:true});console.log(JSON.stringify({orders:db.prepare('SELECT * FROM orders').all(),migrations:db.prepare('SELECT * FROM migrations').all(),config:require('fs').readFileSync('/data/private-config','utf8')}));`);
    const originalDatabase=databaseState();
    fs.mkdirSync(path.join(f.root, 'service'));
    fs.writeFileSync(path.join(f.root, 'service', 'Dockerfile'), 'FROM node:24-alpine\nWORKDIR /app\nCOPY . /app/\nCMD ["node", "server.cjs"]\n');
    fs.writeFileSync(path.join(f.root, 'service', 'server.cjs'), `require('http').createServer((req,res)=>{res.statusCode=req.url==='/private'?401:200;res.end(${JSON.stringify(composeProject)});}).listen(3000,'0.0.0.0');`);
    fs.writeFileSync(path.join(f.root, 'package.json'), JSON.stringify({ name: 'dodo-deployment-fixture', scripts: { test: 'node check.cjs' } }));
    fs.writeFileSync(path.join(f.root, 'check.cjs'), `console.log(JSON.stringify({numTotalTests:1,numPassedTests:1,numFailedTests:0}));`);
    new ProjectRegistry(f.ws.store).add(f.root, 'Disposable Docker fixture');
    const s = f.ws.services, r = s.recovery!, actor = { id: 'local-stdio' };
    await r.checkpoint('owner-checkpoint', actor.id);
    async function verify() {
      const overview = VerificationSchema.parse(await f.call('verify_changes', { mode: 'plan' }));
      const task = overview.recommendedTasks.find(t => t.taskId === 'npm:test')!;
      const checks = [{ taskId: task.taskId, recipeDigest: task.recipeDigest }];
      const result = VerificationSchema.parse(await f.call('verify_changes', { mode: 'run', tasks: checks, sourceDigest: overview.freshness.baselineDigest, idempotencyKey: f.key(), waitMs: 10000 }));
      expect(result.status).toBe('passed'); return { id: result.verificationId!, checks };
    }
    const v = await verify(), port = await freePort();
    const target = await r.deployments.configure({ expectedRevision: 0, enabled: true, confirmDaemonAccess: true, definition: {
      name: 'fixture', adapter: 'docker-compose', dockerContext, composeProject, service: 'web', contextRoot: 'service',
      retainedImages:2, volumes:[{name:volume,target:'/data'}], sourceMapping: { workspaceRoot: 'service', containerRoot: '/app' }, ports: [{ published: port, target: 3000 }],
      requiredChecks: v.checks, health: [{ id: 'ready', kind: 'http', url: `http://127.0.0.1:${port}/health`, allowPrivateNetwork: true },
        { id: 'protected-route', kind: 'http', url: `http://127.0.0.1:${port}/private`, expectedStatus: 401, allowPrivateNetwork: true }], stabilizationMs: 1000, intervalMs: 500,
    } }, () => {});
    async function build(verificationId: string) {
      const p = await r.deployments.prepare({ targetId: target.id, expectedTargetRevision: target.revision, verificationId, idempotencyKey: f.key() }, actor, () => {});
      tags.add(`dodo-recovery:${p.plan.deploymentId}`);
      const built = await f.call('deployment_build', { deploymentId: p.plan.deploymentId, planHash: p.planHash }) as Awaited<ReturnType<typeof r.deployments.build>>;
      expect(built.state, JSON.stringify(built.outcome)).toBe('BUILT'); expect(built.imageDigest).toMatch(/^sha256:/);
      images.add(built.imageDigest!);
      expect(built.outcome).toMatchObject({ source: { state: 'VERIFIED', exactRecoveryAvailable: true } }); return built;
    }
    const a = await build(v.id);
    const apply = async (p: typeof a) => await f.call('deployment_apply', { deploymentId: p.plan.deploymentId, planHash: p.planHash, imageDigest: p.imageDigest }) as Awaited<ReturnType<typeof r.deployments.apply>>;
    const applied = await apply(a);
    expect(applied.state, JSON.stringify(applied.outcome)).toBe('KNOWN_GOOD');
    for (const id of applied.outcome?.['containerIds'] as string[]) containers.add(id);
    const pointer = () => f.ws.store.db.prepare('SELECT deployment_id FROM recovery_production_pointers WHERE target_id=?').get(target.id);
    expect(pointer()).toEqual({ deployment_id: a.plan.deploymentId });
    const replay = await apply(a);
    expect(replay.replayed).toBe(true); expect(replay.outcome).toEqual(applied.outcome);
    // New source is journaled through the same real tool pipeline.
    await f.call('write_file', { path: 'service/server.cjs', content: `require('http').createServer((_req,res)=>{res.statusCode=503;res.end('unhealthy fixture');}).listen(3000,'0.0.0.0');` });
    const b = await build((await verify()).id);
    fs.writeFileSync(path.join(f.root, 'service', 'external.txt'), 'external drift');
    await expect(apply(b)).rejects.toThrow('FILE_CHANGED');
    expect(pointer()).toEqual({ deployment_id: a.plan.deploymentId }); fs.unlinkSync(path.join(f.root, 'service', 'external.txt'));
    const failed = await apply(b);
    expect(failed.state, JSON.stringify(failed.outcome)).toBe('FAILED');
    expect(pointer()).toEqual({ deployment_id: a.plan.deploymentId });
    expect(await apply(b)).toMatchObject({ state: 'FAILED', replayed: true });
    // Rollback is a new reviewed plan, never an implicit response to bad health.
    const rollback = await f.call('deployment_rollback_prepare', { deploymentId: a.plan.deploymentId, idempotencyKey: f.key() }) as typeof a;
    expect(rollback.state).toBe('BUILT');expect(rollback.imageDigest).toBe(a.imageDigest);
    expect(rollback.plan.rollback).toMatchObject({ fromDeploymentId: a.plan.deploymentId });
    const rolledBack = await apply(rollback);
    expect(rolledBack.state, JSON.stringify(rolledBack.outcome)).toBe('KNOWN_GOOD');
    expect(pointer()).toEqual({ deployment_id: rollback.plan.deploymentId });
    expect(fs.readFileSync(path.join(f.root,'service/server.cjs'),'utf8')).toContain('unhealthy fixture');
    const currentContainer = (rolledBack.outcome!['containerIds'] as string[])[0]!;
    containers.add(currentContainer);
    const preview = await f.call('deployment_source_preview', { deploymentId: a.plan.deploymentId }) as { observation: { source: { state: string } }; restore: { planId: string; planHash: string }; containerRestarted: boolean };
    expect(preview.observation.source.state).toBe('VERIFIED');expect(preview.containerRestarted).toBe(false);
    expect(fs.readFileSync(path.join(f.root,'service/server.cjs'),'utf8')).toContain('unhealthy fixture');
    await f.call('restore_apply', { planId: preview.restore.planId, planHash: preview.restore.planHash, idempotencyKey: f.key() });
    expect(fs.readFileSync(path.join(f.root,'service/server.cjs'),'utf8')).toContain(composeProject);
    expect(docker(['container','inspect','--format','{{.State.Running}}',currentContainer])).toBe('true');
    expect(databaseState()).toBe(originalDatabase);
    const dispatch=createIpcDispatcher({ws:f.ws,transport:{kind:'stdio',port:0,locked:true,publicUrl:null},requestStop:()=>{},revalidateOwner:()=>{}});
    const maintenance=(input:unknown)=>dispatch('deployment.maintenance',{workspaceId:f.ws.workspaceId,workspaceEpoch:f.ws.epoch,confirm:true,input}) as Promise<{reviewId:string;reviewHash:string;state:string;replayed?:boolean;observation:{items:Array<{image:string;eligible:boolean;reasons:string[]}>}}>;
    // A matching label cannot certify altered source bytes inside an image.
    await f.call('write_file',{path:'service/Dockerfile',content:'FROM node:24-alpine\nWORKDIR /app\nCOPY . /app/\nLABEL fixture.commit="A"\nRUN echo tampered >> server.cjs\nCMD ["node", "server.cjs"]\n'});
    const vBad=await verify(),pBad=await r.deployments.prepare({targetId:target.id,expectedTargetRevision:target.revision,verificationId:vBad.id,idempotencyKey:f.key()},actor,()=>{});
    tags.add(`dodo-recovery:${pBad.plan.deploymentId}`);
    const bad=await f.call('deployment_build',{deploymentId:pBad.plan.deploymentId,planHash:pBad.planHash}) as typeof a;
    expect(bad.state).toBe('UNKNOWN');expect(bad.imageDigest).toMatch(/^sha256:/);images.add(bad.imageDigest!);
    expect(pointer()).toEqual({deployment_id:rollback.plan.deploymentId});
    const resolution=await maintenance({action:'resolve_preview',deploymentId:bad.plan.deploymentId});
    expect(await maintenance({action:'apply',reviewId:resolution.reviewId,reviewHash:resolution.reviewHash})).toMatchObject({state:'COMPLETED',productionHealthClaim:false});
    expect(r.deployments.inspect(bad.plan.deploymentId,actor)).toMatchObject({state:'UNKNOWN',retention:{uncertaintyAcknowledged:true}});
    const jobsBeforeRetry=f.ws.store.db.prepare('SELECT COUNT(*) AS n FROM jobs').get();
    expect(await f.call('deployment_build',{deploymentId:bad.plan.deploymentId,planHash:bad.planHash})).toMatchObject({state:'UNKNOWN',replayed:true});
    expect(f.ws.store.db.prepare('SELECT COUNT(*) AS n FROM jobs').get()).toEqual(jobsBeforeRetry);
    // Real image cleanup honours pins, current/previous known-good and live refs.
    const cleanup=await maintenance({action:'cleanup_preview',targetId:target.id});
    expect(cleanup.observation.items.find(i=>i.image===b.imageDigest)).toMatchObject({eligible:true});
    await maintenance({action:'pin',deploymentId:b.plan.deploymentId,pinned:true,expectedPinned:false});
    await expect(maintenance({action:'apply',reviewId:cleanup.reviewId,reviewHash:cleanup.reviewHash})).rejects.toThrow('changed since maintenance preview');
    const pinned=await maintenance({action:'cleanup_preview',targetId:target.id});
    expect(pinned.observation.items.find(i=>i.image===b.imageDigest)).toMatchObject({eligible:false,reasons:expect.arrayContaining(['owner_pin'])});
    await maintenance({action:'pin',deploymentId:b.plan.deploymentId,pinned:false,expectedPinned:true});
    const clean=await maintenance({action:'cleanup_preview',targetId:target.id});
    expect(await maintenance({action:'apply',reviewId:clean.reviewId,reviewHash:clean.reviewHash})).toMatchObject({state:'COMPLETED'});
    expect(docker(['image','ls','--quiet','--no-trunc'])).not.toContain(b.imageDigest);
    expect(await maintenance({action:'apply',reviewId:clean.reviewId,reviewHash:clean.reviewHash})).toMatchObject({state:'COMPLETED',replayed:true});
    expect(r.deployments.inspect(b.plan.deploymentId,actor).retention.imageRetired).toBe(true);
    // Simulate an interrupted receipt after successful daemon removal: inspection
    // records the actual absence without repeating image rm.
    f.ws.store.db.prepare('UPDATE recovery_deployment_maintenance SET retired=0,cleanup_json=? WHERE deployment_id=?').run(JSON.stringify({state:'UNKNOWN'}),b.plan.deploymentId);
    const imageReview=await maintenance({action:'image_preview',deploymentId:b.plan.deploymentId});
    expect(await maintenance({action:'apply',reviewId:imageReview.reviewId,reviewHash:imageReview.reviewHash})).toMatchObject({state:'COMPLETED'});
    expect(r.deployments.inspect(b.plan.deploymentId,actor).retention.imageRetired).toBe(true);
    // Durable probe identity survives an interrupted build; never remove a
    // changed/running container merely because its name looks like a probe.
    const probe={name:newId('dodo-source-probe'),claim:newId('probeclaim'),image:a.imageDigest!,removed:false};
    const probeId=docker(['container','create','--network','none','--name',probe.name,'--label',`dodo.recovery.probe=${probe.claim}`,'--entrypoint','/dodo-never-executed',a.imageDigest!]);containers.add(probeId);
    f.ws.store.db.prepare('UPDATE recovery_deployment_maintenance SET probe_json=? WHERE deployment_id=?').run(JSON.stringify({...probe,id:probeId,claim:newId('probeclaim')}),a.plan.deploymentId);
    await expect(maintenance({action:'probe_preview',deploymentId:a.plan.deploymentId})).rejects.toThrow('probe identity');
    expect(docker(['container','inspect','--format','{{.State.Running}}',probeId])).toBe('false');
    f.ws.store.db.prepare('UPDATE recovery_deployment_maintenance SET probe_json=? WHERE deployment_id=?').run(JSON.stringify({...probe,id:probeId}),a.plan.deploymentId);
    const probeReview=await maintenance({action:'probe_preview',deploymentId:a.plan.deploymentId});
    expect(await maintenance({action:'apply',reviewId:probeReview.reviewId,reviewHash:probeReview.reviewHash})).toMatchObject({state:'COMPLETED'});
    expect(r.deployments.inspect(a.plan.deploymentId,actor).retention.unfinishedProbe).toBe(false);

    expect(databaseState()).toBe(originalDatabase);
    expect(docker(['container','inspect','--format','{{.State.Running}}',currentContainer])).toBe('true');

  }, 240000);
});
